name: CAG_App
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^8.0.0

  flutter_svg: ^2.2.4
  google_fonts: ^8.0.2
  mobile_scanner: ^7.2.0
  url_launcher: ^6.3.2

  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0        # GPS vị trí hiện tại
  dio: ^5.4.0

  flutter_dotenv: ^5.0.2               
  http: ^1.6.0
  intl: ^0.20.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/icons/
      - .env
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/CAGPRO_logoonly.png"

